### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by jeffrey-w**

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
try to put every aspect of the code in seperate file - example all router.post(feed stuff) in feed.js
all login stuff in login.js etc.. then cleanup should be finished... for common methods you can put in common.js and db in db.js or whatever you like... just so we don't have 1 file to work on which is a pain to scroll top to bottom all the time
edit : look for module exports

**Comment by DavidLiang01** [comment]
When you COMMIT, put a DESCRIPTION, so that we know what you changed

**Comment by Mounceph99** [comment]
Don't forget to remove the avatar/setting icon on left navbar
and 'Scrap' button on user pages

**Comment by jeffrey-w** [comment]
Deprecated (see #93 )

**Pull request closed without merging**
